name: Release module version
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@12401d756af5e640fe29af8910d03d292d240cbb # v10.0.0
